//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;


namespace NewNamespace
{
    
    #region Service
    public class DictionaryHeaderAttribute : Attribute
    {
        private int _number;
        public int Number
        {
            get
            {
                return this._number;
            }
            set
            {
                this._number = value;
            }
        }
    }
    #endregion
    /// <summary>
    ///  Состояние записи
    /// </summary>
    [DictionaryHeader(Number=1)]
    public enum RowState
    {
        [Description("")]
        Allowed = 1,
        [Description("")]
        Denied = 2,
    }
    /// <summary>
    ///  Состояние пользователя
    /// </summary>
    [DictionaryHeader(Number=2)]
    public enum ClientState
    {
        [Description("")]
        Pending = 1,
        [Description("")]
        Active = 2,
        [Description("")]
        Blocked = 3,
        [Description("")]
        Deleted = 4,
    }
    /// <summary>
    ///  Тип пользователя
    /// </summary>
    [DictionaryHeader(Number=3)]
    public enum ClientType
    {
        [Description("")]
        Ordinary = 1,
        [Description("")]
        Superuser = 2,
        [Description("")]
        Bot = 3,
    }
    /// <summary>
    ///  Состояние счета 
    /// </summary>
    [DictionaryHeader(Number=4)]
    public enum MT4AccountState
    {
        [Description("")]
        NotChecked = 1,
        [Description("")]
        Valid = 2,
        [Description("")]
        InvalidCredential = 3,
        [Description("")]
        InvalidCurrency = 4,
        [Description("")]
        ServerNotResponding = 5,
        [Description("")]
        Blocked = 6,
        [Description("")]
        Deleted = 7,
    }
    /// <summary>
    ///  Команда
    /// </summary>
    [DictionaryHeader(Number=6)]
    public enum RawOrderCommand
    {
        [Description("")]
        Buy = 1,
        [Description("")]
        Sell = 2,
        [Description("")]
        Deposit = 3,
        [Description("")]
        Balance = 4,
    }
    /// <summary>
    ///  Результат
    /// </summary>
    [DictionaryHeader(Number=7)]
    public enum PaymentSystemResponseResult
    {
        [Description("")]
        Success = 1,
        [Description("")]
        Fail = 2,
    }
    /// <summary>
    ///  Тип операции
    /// </summary>
    [DictionaryHeader(Number=8)]
    public enum FinancialTransactionType
    {
        [Description("")]
        Deposit = 1,
        [Description("")]
        Withdrawal = 2,
        [Description("")]
        ContestFee = 3,
        [Description("")]
        ContestBuyin = 4,
        [Description("")]
        ContestReward = 5,
        [Description("")]
        ContestCancellation = 6,
    }
    /// <summary>
    ///  Статус операции
    /// </summary>
    [DictionaryHeader(Number=9)]
    public enum FinancialTransactionStatus
    {
        [Description("")]
        Pending = 1,
        [Description("")]
        Approved = 2,
        [Description("")]
        Rejected = 3,
        [Description("")]
        Canceled = 4,
        [Description("")]
        Frozen = 5,
    }
    /// <summary>
    ///  Единица измерения
    /// </summary>
    [DictionaryHeader(Number=10)]
    public enum FinancialTransactionUnit
    {
        [Description("")]
        USD = 1,
        [Description("")]
        Point = 2,
    }
    /// <summary>
    ///  Инициатор операции
    /// </summary>
    [DictionaryHeader(Number=11)]
    public enum FinancialTransactionInitiator
    {
        [Description("")]
        User = 1,
        [Description("")]
        Admin = 2,
    }
    /// <summary>
    ///  Платежная система
    /// </summary>
    [DictionaryHeader(Number=12)]
    public enum FinancialTransactionPaymentSystem
    {
        [Description("")]
        WM = 1,
        [Description("")]
        LR = 2,
        [Description("")]
        PO = 3,
        [Description("")]
        DO = 4,
        [Description("")]
        DP = 5,
    }
    /// <summary>
    ///  Состояние турнира
    /// </summary>
    [DictionaryHeader(Number=13)]
    public enum ContestState
    {
        [Description("")]
        Active = 1,
        [Description("")]
        NeedCalculation = 2,
        [Description("")]
        Calculated = 3,
        [Description("")]
        Canceled = 4,
        [Description("")]
        Deleted = 5,
        [Description("")]
        Template = 6,
    }
    /// <summary>
    ///  Тип турнира
    /// </summary>
    [DictionaryHeader(Number=14)]
    public enum ContestType
    {
        [Description("")]
        Custom = 1,
        [Description("")]
        Sitngo = 2,
        [Description("")]
        Regular = 3,
        [Description("")]
        Freeroll = 4,
    }
    /// <summary>
    ///  Периодичность турнира
    /// </summary>
    [DictionaryHeader(Number=15)]
    public enum ContestPeriodicity
    {
        [Description("")]
        NotPeriodical = 1,
        [Description("")]
        Daily = 2,
        [Description("")]
        Weekly = 3,
        [Description("")]
        Monthly = 4,
    }
    /// <summary>
    ///  Правило выплаты вознаграждения
    /// </summary>
    [DictionaryHeader(Number=16)]
    public enum ContestRewardRule
    {
        [Description("")]
        Custom = 1,
        [Description("")]
        ThreeWinners = 2,
        [Description("")]
        FiftyFifty = 3,
    }
    /// <summary>
    ///  Состояние участника турнира
    /// </summary>
    [DictionaryHeader(Number=17)]
    public enum ContestAccountState
    {
        [Description("")]
        Active = 1,
        [Description("")]
        Canceled = 2,
        [Description("")]
        Banned = 3,
        [Description("")]
        NeedCalculation = 4,
        [Description("")]
        Calculated = 5,
    }
    /// <summary>
    ///  Атрибут
    /// </summary>
    [DictionaryHeader(Number=18)]
    public enum ClientExtensionAttribute
    {
        [Description("")]
        MoneyBalance = 1,
    }
}
