//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class admins : BaseModel
    {
        private EAdminType _admin_id;
    	public EAdminType admin_id 
    	{ 
    		get { return _admin_id; } 
    		set
    		{
    			if (value != _admin_id) {
    				_admin_id = value;
    				 OnPropertyChanged("admin_id");
    			}
    		} 
    	}
    
        private string _admin_login;
    	public string admin_login 
    	{ 
    		get { return _admin_login; } 
    		set
    		{
    			if (value != _admin_login) {
    				_admin_login = value;
    				 OnPropertyChanged("admin_login");
    			}
    		} 
    	}
    
        private string _admin_password;
    	public string admin_password 
    	{ 
    		get { return _admin_password; } 
    		set
    		{
    			if (value != _admin_password) {
    				_admin_password = value;
    				 OnPropertyChanged("admin_password");
    			}
    		} 
    	}
    
    }
}
